# Chart Releaser configuration
# https://github.com/helm/chart-releaser

# Git owner/repo
owner: Hillyon-Labs
git-repo: opsctrl_daemon

# GitHub Pages branch for chart repository
pages-branch: gh-pages

# Mark releases as pre-release if version contains hyphen (e.g., 1.0.0-rc1)
release-name-template: "{{ .Name }}-{{ .Version }}"

# Generate release notes from commits
generate-release-notes: true

# Package path
packages-with-index: true
