/**
 * Time constants in milliseconds for consistent usage across the application
 * 
 * This file centralizes all time-related constants to avoid hardcoding values
 * and ensure consistency in validation rules and application logic.
 */

// Base time units
export const ONE_SECOND_IN_MILLISECONDS = 1000;
export const ONE_MINUTE_IN_MILLISECONDS = 60 * ONE_SECOND_IN_MILLISECONDS;
export const ONE_HOUR_IN_MILLISECONDS = 60 * ONE_MINUTE_IN_MILLISECONDS;
export const ONE_DAY_IN_MILLISECONDS = 24 * ONE_HOUR_IN_MILLISECONDS;

// Common short durations
export const FIVE_SECONDS_IN_MILLISECONDS = 5 * ONE_SECOND_IN_MILLISECONDS;
export const TEN_SECONDS_IN_MILLISECONDS = 10 * ONE_SECOND_IN_MILLISECONDS;
export const THIRTY_SECONDS_IN_MILLISECONDS = 30 * ONE_SECOND_IN_MILLISECONDS;

// Common medium durations
export const FIVE_MINUTES_IN_MILLISECONDS = 5 * ONE_MINUTE_IN_MILLISECONDS;
export const TEN_MINUTES_IN_MILLISECONDS = 10 * ONE_MINUTE_IN_MILLISECONDS;
export const THIRTY_MINUTES_IN_MILLISECONDS = 30 * ONE_MINUTE_IN_MILLISECONDS;

// Specific timeouts and limits
export const DIAGNOSIS_MIN_TIMEOUT_MS = FIVE_SECONDS_IN_MILLISECONDS;
export const DIAGNOSIS_MAX_TIMEOUT_MS = FIVE_MINUTES_IN_MILLISECONDS;
export const DIAGNOSIS_DEFAULT_TIMEOUT_MS = THIRTY_SECONDS_IN_MILLISECONDS;

export const DIAGNOSIS_CACHE_MIN_TTL_MS = ONE_MINUTE_IN_MILLISECONDS;
export const DIAGNOSIS_CACHE_MAX_TTL_MS = ONE_DAY_IN_MILLISECONDS;
export const DIAGNOSIS_CACHE_DEFAULT_TTL_MS = FIVE_MINUTES_IN_MILLISECONDS;

export const MAX_PENDING_DURATION_MIN_MS = THIRTY_SECONDS_IN_MILLISECONDS;
export const MAX_PENDING_DURATION_MAX_MS = ONE_HOUR_IN_MILLISECONDS;
export const MAX_PENDING_DURATION_DEFAULT_MS = TEN_MINUTES_IN_MILLISECONDS;

// Alert and backoff timing
export const ALERT_BACKOFF_MIN_MS = 100;
export const ALERT_BACKOFF_MAX_MS = ONE_MINUTE_IN_MILLISECONDS;
export const ALERT_BACKOFF_DEFAULT_MS = ONE_SECOND_IN_MILLISECONDS;

export const ALERT_MAX_BACKOFF_MIN_MS = ONE_SECOND_IN_MILLISECONDS;
export const ALERT_MAX_BACKOFF_MAX_MS = FIVE_MINUTES_IN_MILLISECONDS;
export const ALERT_MAX_BACKOFF_DEFAULT_MS = THIRTY_SECONDS_IN_MILLISECONDS;

// Reconnection timing
export const RECONNECTION_BACKOFF_MIN_MS = 100;
export const RECONNECTION_BACKOFF_MAX_MS = ONE_MINUTE_IN_MILLISECONDS;
export const RECONNECTION_BACKOFF_DEFAULT_MS = ONE_SECOND_IN_MILLISECONDS;

export const RECONNECTION_MAX_BACKOFF_MIN_MS = ONE_SECOND_IN_MILLISECONDS;
export const RECONNECTION_MAX_BACKOFF_MAX_MS = TEN_MINUTES_IN_MILLISECONDS;
export const RECONNECTION_MAX_BACKOFF_DEFAULT_MS = THIRTY_SECONDS_IN_MILLISECONDS;

// Rate limiting
export const ALERT_RATE_LIMIT_MAX_MINUTES = 24 * 60; // 24 hours
export const ALERT_RATE_LIMIT_DEFAULT_MINUTES = 5;